version: '3'
services:
  gitlab:
    # build: .
    image: gitlab/gitlab-ce
    container_name: gitlab
    host: buaamc2.net
    ports:
      - "8081:80"
      - "443:443"
      - "222:22"
    volumes:
      # - config/gitlab.rb:/etc/gitlab/gitlab.rb
      - /root/gitlab/config:/etc/gitlab
      - /root/gitlab/logs:/var/log/gitlab
      - /root/gitlab/data:/var/opt/gitlab
      