version: '3'
services:
  machinenginx:
    build: .
    command: bash -c "service nginx start && python3 code/get_user.py"
    ports:
      - "82:82"
    volumes:
      - .:/src
      - ./nginx:/etc/nginx/conf.d