version: '3'
services:
  machinenginx:
    build: .
    environment:
      - user=${user}
      - passwd=${passwd}
      - key=${key}
    command: bash -c "service nginx start && python3 code/get_user_remote.py > /src/machine.log 2>&1 && python3 code/aliyun.py"
    ports:
      - "82:82"
    volumes:
      - .:/src
      - ./nginx:/etc/nginx/conf.d